/**
 * Peggy.js 解析器生成脚本
 *
 * 用法：
 *   npx tsx parser/build.ts           # 生成 src/parser.ts
 *   npm run parser:build              # 同上
 *
 * 输入：parser/sysml.pegjs
 * 输出：parser/parser.generated.ts（CommonJS，TypeScript）
 *
 * 之所以生成到 .ts 而不是 .js：
 *   - 与项目整体 TS 工具链一致（直接被其他 .ts 文件 import）
 *   - 仍可作为 CommonJS 模块运行（peg.generate 输出格式兼容）
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';
import peggy from 'peggy';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const GRAMMAR_PATH = path.join(__dirname, 'sysml.pegjs');
const OUTPUT_PATH = path.join(__dirname, 'parser.generated.ts');

const source = fs.readFileSync(GRAMMAR_PATH, 'utf-8');

const generated = peggy.generate(source, {
  output: 'source',
  format: 'es',
  allowedStartRules: ['File'],
});

// 把 options.source 改写为 globalThis 访问，避开 peggy dependency 序列化的坑
// 生成的代码里 peg$parse(input, options) 内部用 options.source 读源码；
// 我们把它替换为 globalThis.__SYSML_SOURCE（在 parser.ts 中设置）
const patched = generated
  .replace(/options\.source/g, 'globalThis.__SYSML_SOURCE')
  // 同时去掉 peggy 自动生成的对 options 的判空，
  // 我们的 wrapper 总是传入 options
  .replace(/options\s*=\s*options\s*\|\|\s*\{\s*\};/g, 'options = options || {};')

// 把生成的 ES 代码包装成 TS 模块
// @ts-nocheck：生成器输出未严格类型化，tsc 检查会触发大量误报；
// 真实类型由 parser.ts 包装层负责。
const banner = `// Auto-generated by parser/build.ts — do not edit.
// Generated at ${new Date().toISOString()}
// @ts-nocheck

`;

const tsSource = banner + generated + '\n';

fs.writeFileSync(OUTPUT_PATH, tsSource, 'utf-8');
console.log(`✓ Generated ${path.relative(process.cwd(), OUTPUT_PATH)} (${tsSource.length} bytes)`);
